on:
  schedule:
    - cron: "20 * * * *"
  push:
  workflow_dispatch:
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: HalleyAssist/git-sync@v3
        with:
          source_repo: "git://git.yoctoproject.org/poky"
          source_branch: "*"
          destination_repo: "HalleyAssist/poky"
          destination_branch: "*"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
